@extends('layouts.site')
@section('description','Publication and visual design by Rovinya Wolff. Explore directories, magazines, posters, and social media design.')
@section('content')
<section class="editorial-gradient overflow-hidden"><div class="site-container grid min-h-[78vh] items-center gap-14 py-20 lg:grid-cols-[1.05fr_.95fr] lg:py-28"><div><p class="eyebrow">{{ $settings->professional_title }}</p><h1 class="display-title mt-6">{{ $settings->hero_heading }} <em class="text-[#8d4f7f]">{{ $settings->hero_accent }}</em></h1><p class="section-copy">{{ $settings->hero_intro }}</p><div class="mt-8 flex flex-wrap gap-3"><a href="{{ route('work') }}" class="button-primary">Explore my work</a><a href="{{ route('contact') }}" class="button-secondary">Discuss a project</a></div><p class="mt-8 text-sm text-[#786b73] dark:text-[#b9acb4]">{{ $settings->availability }}</p></div>
<div class="relative mx-auto w-full max-w-lg" aria-hidden="true"><div class="absolute -left-6 top-16 h-72 w-52 rotate-[-9deg] rounded-sm bg-[#e67866] opacity-70"></div><div class="book-shadow relative ml-auto aspect-[3/4] w-[72%] rotate-[4deg] rounded-sm border-8 border-white bg-[#6f3b67] p-8 text-white"><p class="text-xs uppercase tracking-[.25em]">Selected works</p><div class="mt-24 font-[family-name:var(--font-display)] text-5xl leading-none">Stories,<br><em>beautifully</em><br>arranged.</div><p class="absolute bottom-8 text-sm">Rovinya Wolff</p></div><div class="absolute -bottom-8 left-3 rounded-full bg-[#f4d4b7] px-6 py-4 text-sm font-bold text-[#5e3558]">Editorial • Social • Print</div></div></div></section>
<section class="site-container py-24"><div class="grid gap-8 lg:grid-cols-[.65fr_1fr]"><div><p class="eyebrow">What I design</p><h2 class="section-title mt-4">Clear ideas, made visually memorable.</h2></div><div class="grid gap-4 sm:grid-cols-2">@foreach($services as $service)<article class="service-card"><span class="text-sm text-[#e67866]">0{{ $loop->iteration }}</span><h3 class="mt-8 font-[family-name:var(--font-display)] text-3xl">{{ $service->title }}</h3><p class="mt-4 leading-7 text-[#6d6269] dark:text-[#cfc4ca]">{{ $service->description }}</p></article>@endforeach</div></div><div class="mt-10 text-right"><a href="{{ route('services') }}" class="font-bold text-[#8d4f7f]">See all services →</a></div></section>
<section class="border-y bg-[#241d24] py-24 text-[#fbf6ef]"><div class="site-container"><div class="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p class="eyebrow text-[#f4a696]">Selected portfolio</p><h2 class="section-title mt-4">Work made to be seen and remembered.</h2></div><a href="{{ route('work') }}" class="text-sm font-bold">View all work →</a></div><div class="mt-12 grid gap-6 md:grid-cols-2">@forelse($projects as $project)<article class="project-card border-white/10 bg-white/5"><a href="{{ route('work.show',$project) }}" class="block">@if($project->image_path)<img src="{{ asset('storage/'.$project->image_path) }}" alt="{{ $project->title }}" class="aspect-[4/3] w-full object-cover" loading="lazy">@else<div class="grid aspect-[4/3] place-items-center bg-gradient-to-br from-[#6f3b67] to-[#e67866]"><span class="font-[family-name:var(--font-display)] text-4xl">{{ $project->title }}</span></div>@endif<div class="p-7"><p class="text-xs uppercase tracking-[.2em] text-[#f4a696]">{{ $project->category }}</p><h3 class="mt-3 font-[family-name:var(--font-display)] text-3xl">{{ $project->title }}</h3><p class="mt-3 text-[#d5cad0]">{{ $project->summary }}</p></div></a></article>@empty<p class="text-[#d5cad0]">The first projects are being prepared for the portfolio.</p>@endforelse</div></div></section>
<section class="site-container py-24 text-center"><p class="eyebrow">Have something in mind?</p><h2 class="section-title mx-auto mt-4 max-w-3xl">Let’s give your next publication or campaign a visual voice.</h2><a class="button-primary mt-8" href="{{ route('contact') }}">Tell me about it</a></section>
@endsection
