<!DOCTYPE html><html lang="en" class="scroll-smooth"><head>
@php($metaTitle=trim($__env->yieldContent('title'))?:$settings->name.' | '.$settings->professional_title)
@php($metaDescription=trim($__env->yieldContent('description'))?:'Rovinya Wolff designs publications, directories, posters, and social media visuals.')
@php($metaImage=asset('images/social-card.svg'))
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="{{ $metaDescription }}"><meta name="theme-color" content="#6f3b67"><link rel="canonical" href="{{ url()->current() }}">
<meta property="og:type" content="website"><meta property="og:site_name" content="{{ $settings->name }}"><meta property="og:title" content="{{ $metaTitle }}"><meta property="og:description" content="{{ $metaDescription }}"><meta property="og:url" content="{{ url()->current() }}"><meta property="og:image" content="{{ $metaImage }}"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="{{ asset('images/favicon.svg') }}" type="image/svg+xml"><title>{{ $metaTitle }}</title>
<script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'Person','name'=>$settings->name,'url'=>route('home'),'jobTitle'=>$settings->professional_title,'email'=>'mailto:'.$settings->email,'sameAs'=>array_values(array_filter([$settings->linkedin_url,$settings->instagram_url,$settings->behance_url])),'knowsAbout'=>['Publication design','Editorial design','Social media design','Poster design']],JSON_UNESCAPED_SLASHES) !!}</script>
<script>(()=>{const s=localStorage.getItem('theme');document.documentElement.classList.toggle('dark',s?s==='dark':matchMedia('(prefers-color-scheme:dark)').matches)})()</script>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-[#fbf6ef] text-[#211b26] antialiased transition-colors dark:bg-[#1b161c] dark:text-[#f9f1eb]"><div class="paper-noise pointer-events-none fixed inset-0 -z-10 opacity-70"></div>
<header class="sticky top-0 z-50 border-b bg-[#fbf6ef]/85 backdrop-blur-xl dark:bg-[#1b161c]/85"><nav class="site-container flex h-20 items-center justify-between" aria-label="Main navigation"><a href="{{ route('home') }}" class="flex items-center gap-3"><span class="grid size-10 place-items-center rounded-full bg-[#6f3b67] font-[family-name:var(--font-display)] text-xl italic text-white">R</span><span><strong class="block font-[family-name:var(--font-display)] text-lg font-normal">{{ $settings->name }}</strong><small class="block text-[10px] uppercase tracking-[.18em] text-[#8b7e86]">Visual designer</small></span></a>
<div class="hidden items-center gap-7 text-sm md:flex">@foreach(['home'=>'Home','work'=>'Portfolio','services'=>'Services','about'=>'About','contact'=>'Contact'] as $route=>$label)<a class="nav-link {{ request()->routeIs($route.'*')?'active':'' }}" href="{{ route($route) }}">{{ $label }}</a>@endforeach</div><div class="flex items-center gap-2"><button data-theme-toggle class="icon-button" aria-label="Switch colour theme"><span class="dark:hidden">☾</span><span class="hidden dark:inline">☀</span></button><button data-menu-toggle class="icon-button md:hidden" aria-expanded="false" aria-controls="mobile-menu" aria-label="Open navigation">☰</button><a class="button-primary ml-2 hidden sm:inline-flex" href="{{ route('contact') }}">Start a project</a></div></nav>
<div id="mobile-menu" data-mobile-menu class="site-container hidden border-t py-4 md:hidden"><div class="grid text-sm">@foreach(['home'=>'Home','work'=>'Portfolio','services'=>'Services','about'=>'About','contact'=>'Contact'] as $route=>$label)<a class="mobile-link" href="{{ route($route) }}">{{ $label }}</a>@endforeach</div></div></header>
<main>@yield('content')</main><footer class="border-t py-10"><div class="site-container flex flex-col gap-5 text-sm text-[#786b73] sm:flex-row sm:items-center sm:justify-between dark:text-[#b9acb4]"><p>© {{ date('Y') }} {{ $settings->name }}. Designed with care.</p><div class="flex flex-wrap gap-5">@if($settings->instagram_url)<a href="{{ $settings->instagram_url }}">Instagram</a>@endif @if($settings->behance_url)<a href="{{ $settings->behance_url }}">Behance</a>@endif @if($settings->linkedin_url)<a href="{{ $settings->linkedin_url }}">LinkedIn</a>@endif<a href="mailto:{{ $settings->email }}">Email</a><a href="{{ route('privacy') }}">Privacy</a></div></div></footer></body></html>
