<!DOCTYPE html><html lang="en" class="scroll-smooth"><head>
@php($metaTitle=trim($__env->yieldContent('title'))?:$settings->name.' | '.$settings->professional_title)
@php($metaDescription=trim($__env->yieldContent('description'))?:'Rovinya Wolff creates publication design, social media visuals, and memorable brand experiences.')
@php($metaImage=asset('images/social-card.svg'))
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="{{ $metaDescription }}"><meta name="theme-color" content="#151217"><link rel="canonical" href="{{ url()->current() }}">
<meta property="og:type" content="website"><meta property="og:site_name" content="{{ $settings->name }}"><meta property="og:title" content="{{ $metaTitle }}"><meta property="og:description" content="{{ $metaDescription }}"><meta property="og:url" content="{{ url()->current() }}"><meta property="og:image" content="{{ $metaImage }}"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="{{ asset('images/favicon.svg') }}" type="image/svg+xml"><title>{{ $metaTitle }}</title>
<script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'Person','name'=>$settings->name,'url'=>route('home'),'jobTitle'=>$settings->professional_title,'email'=>'mailto:'.$settings->email,'sameAs'=>array_values(array_filter([$settings->linkedin_url,$settings->instagram_url,$settings->behance_url])),'knowsAbout'=>['Publication design','Editorial design','Social media design','Poster design']],JSON_UNESCAPED_SLASHES) !!}</script>
<script>(()=>{const s=localStorage.getItem('theme');document.documentElement.classList.toggle('dark',s?s==='dark':matchMedia('(prefers-color-scheme:dark)').matches)})()</script>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen overflow-x-hidden bg-[#f8f5f2] text-[#171318] antialiased transition-colors dark:bg-[#100e12] dark:text-[#fffaf6]"><div class="ambient pointer-events-none fixed inset-0 -z-10" data-ambient></div>
<header class="fixed inset-x-0 top-0 z-50 px-3 pt-3 sm:px-5"><nav class="site-container flex h-16 items-center justify-between rounded-full border border-black/10 bg-[#f8f5f2]/75 px-4 shadow-[0_10px_40px_rgba(25,15,24,.08)] backdrop-blur-xl dark:border-white/10 dark:bg-[#171318]/70" aria-label="Main navigation"><a href="{{ route('home') }}" class="flex items-center gap-3"><span class="logo-orbit"><i></i><b>R</b></span><span class="hidden sm:block"><strong class="block text-sm">{{ $settings->name }}</strong><small class="block text-[9px] uppercase tracking-[.2em] opacity-55">Visual designer</small></span></a>
<div class="hidden items-center gap-7 text-sm font-semibold md:flex"><a class="nav-link {{ request()->routeIs('home')?'active':'' }}" href="{{ route('home') }}">Home</a><div class="group relative"><a class="nav-link {{ request()->routeIs('work*')?'active':'' }}" href="{{ route('work') }}">Work <span class="text-[10px]">↓</span></a><div class="invisible absolute left-1/2 top-full w-56 -translate-x-1/2 translate-y-2 pt-4 opacity-0 transition group-hover:visible group-hover:translate-y-0 group-hover:opacity-100"><div class="rounded-2xl border bg-[#f8f5f2] p-2 shadow-2xl dark:bg-[#1b171d]"><a class="mobile-link block" href="{{ route('work.publications') }}">Publication design</a><a class="mobile-link block" href="{{ route('work.social') }}">Social media & campaigns</a><a class="mobile-link block" href="{{ route('work') }}">View everything</a></div></div></div><a class="nav-link {{ request()->routeIs('about')?'active':'' }}" href="{{ route('about') }}">About me</a><a class="nav-link {{ request()->routeIs('contact*')?'active':'' }}" href="{{ route('contact') }}">Contact</a></div>
<div class="flex items-center gap-2"><button data-theme-toggle class="icon-button" aria-label="Switch colour theme"><span class="dark:hidden">☾</span><span class="hidden dark:inline">☀</span></button><button data-menu-toggle class="icon-button md:hidden" aria-expanded="false" aria-controls="mobile-menu" aria-label="Open navigation">☰</button><a class="button-primary ml-1 hidden sm:inline-flex" href="{{ route('contact') }}">Let’s create</a></div></nav>
<div id="mobile-menu" data-mobile-menu class="site-container mt-2 hidden rounded-[1.75rem] border bg-[#f8f5f2]/95 p-3 shadow-2xl backdrop-blur-xl md:hidden dark:bg-[#171318]/95"><div class="grid text-sm font-semibold"><a class="mobile-link" href="{{ route('home') }}">Home</a><a class="mobile-link" href="{{ route('work') }}">All work</a><a class="mobile-link pl-8" href="{{ route('work.publications') }}">↳ Publication design</a><a class="mobile-link pl-8" href="{{ route('work.social') }}">↳ Social media & campaigns</a><a class="mobile-link" href="{{ route('about') }}">About me</a><a class="mobile-link" href="{{ route('contact') }}">Contact</a></div></div></header>
<main>@yield('content')</main><footer class="border-t border-black/10 py-12 dark:border-white/10"><div class="site-container flex flex-col gap-6 text-sm opacity-65 sm:flex-row sm:items-center sm:justify-between"><p>© {{ date('Y') }} {{ $settings->name }}. Make it mean something.</p><div class="flex flex-wrap gap-5">@if($settings->instagram_url)<a href="{{ $settings->instagram_url }}">Instagram</a>@endif @if($settings->behance_url)<a href="{{ $settings->behance_url }}">Behance</a>@endif @if($settings->linkedin_url)<a href="{{ $settings->linkedin_url }}">LinkedIn</a>@endif<a href="mailto:{{ $settings->email }}">Email</a><a href="{{ route('privacy') }}">Privacy</a></div></div></footer></body></html>
