@extends('layouts.site')
@section('title',$project->title.' | '.$settings->name)
@section('description',$project->summary)
@section('content')
<article><header class="site-container py-16 sm:py-24"><a href="{{ route('work') }}" class="text-sm font-bold text-[#8d4f7f]">← Portfolio</a><div class="mt-10 grid gap-10 lg:grid-cols-[1fr_.45fr] lg:items-end"><div><p class="eyebrow">{{ $project->category }}</p><h1 class="display-title mt-5">{{ $project->title }}</h1><p class="section-copy">{{ $project->summary }}</p></div><dl class="grid grid-cols-2 gap-5 rounded-[2rem] border p-6 text-sm"><div><dt class="text-[#8b7e86]">Type</dt><dd class="mt-1 font-bold capitalize">{{ $project->type }}</dd></div>@if($project->organization || $project->client)<div><dt class="text-[#8b7e86]">For</dt><dd class="mt-1 font-bold">{{ $project->organization ?: $project->client }}</dd></div>@endif @if($project->published_at)<div><dt class="text-[#8b7e86]">Date</dt><dd class="mt-1 font-bold">{{ $project->published_at->format('Y') }}</dd></div>@endif @if($project->status)<div><dt class="text-[#8b7e86]">Status</dt><dd class="mt-1 font-bold">{{ $project->status }}</dd></div>@endif</dl></div></header>
@if($project->pdf_path)<section class="border-y bg-[#241d24] py-10 text-white"><div class="site-container"><div class="flipbook-shell" data-flipbook data-pdf-url="{{ asset('storage/'.$project->pdf_path) }}"><div class="mb-5 flex flex-wrap items-center justify-between gap-3"><p data-flipbook-status class="text-sm text-[#d5cad0]">Preparing publication…</p><div class="flex gap-2"><button data-flip-prev class="button-secondary border-white/20 bg-white/5 text-white">← Previous</button><button data-flip-next class="button-secondary border-white/20 bg-white/5 text-white">Next →</button><button data-flip-fullscreen class="button-secondary border-white/20 bg-white/5 text-white">Fullscreen</button></div></div><div data-flipbook-stage class="mx-auto min-h-[420px] w-full overflow-hidden"></div><div class="mt-4 flex justify-center gap-4 text-sm text-[#d5cad0]"><span data-flip-page>Page 1</span>@if($project->is_downloadable)<a href="{{ asset('storage/'.$project->pdf_path) }}" download class="font-bold text-[#f4a696]">Download PDF</a>@endif</div></div></div></section>@elseif($project->image_path)<section class="site-container pb-12"><img src="{{ asset('storage/'.$project->image_path) }}" alt="{{ $project->title }}" class="mx-auto max-h-[80vh] rounded-[2rem] object-contain shadow-2xl"></section>@endif
<section class="site-container py-20"><div class="grid gap-12 lg:grid-cols-2">@if($project->challenge)<div><p class="eyebrow">The brief</p><p class="mt-4 whitespace-pre-line text-lg leading-8 text-[#6d6269] dark:text-[#cfc4ca]">{{ $project->challenge }}</p></div>@endif @if($project->solution)<div><p class="eyebrow">The design</p><p class="mt-4 whitespace-pre-line text-lg leading-8 text-[#6d6269] dark:text-[#cfc4ca]">{{ $project->solution }}</p></div>@endif</div>@if($project->gallery)<div class="mt-16 grid gap-6 sm:grid-cols-2">@foreach($project->gallery as $image)<img src="{{ asset('storage/'.$image) }}" alt="{{ $project->title }} design {{ $loop->iteration }}" class="w-full rounded-[2rem] border object-cover" loading="lazy">@endforeach</div>@endif</section>
<nav class="site-container grid gap-4 pb-24 sm:grid-cols-2">@if($previous)<a class="service-card" href="{{ route('work.show',$previous) }}"><small>Previous project</small><strong class="mt-2 block font-[family-name:var(--font-display)] text-2xl">{{ $previous->title }}</strong></a>@endif @if($next)<a class="service-card text-right sm:col-start-2" href="{{ route('work.show',$next) }}"><small>Next project</small><strong class="mt-2 block font-[family-name:var(--font-display)] text-2xl">{{ $next->title }}</strong></a>@endif</nav></article>
@endsection
