@extends('layouts.site')
@section('title',$project->title.' | '.$settings->name)
@section('description',$project->summary)
@section('content')
<article><header class="site-container py-16 sm:py-24"><a href="{{ route('work') }}" class="text-sm font-bold text-[#8d4f7f]">← Portfolio</a><div class="mt-10 grid gap-10 lg:grid-cols-[1fr_.45fr] lg:items-end"><div><p class="eyebrow">{{ $project->category }}</p><h1 class="display-title mt-5">{{ $project->title }}</h1><p class="section-copy">{{ $project->summary }}</p></div><dl class="grid grid-cols-2 gap-5 rounded-[2rem] border p-6 text-sm"><div><dt class="text-[#8b7e86]">Type</dt><dd class="mt-1 font-bold capitalize">{{ $project->type }}</dd></div>@if($project->organization || $project->client)<div><dt class="text-[#8b7e86]">For</dt><dd class="mt-1 font-bold">{{ $project->organization ?: $project->client }}</dd></div>@endif @if($project->published_at)<div><dt class="text-[#8b7e86]">Date</dt><dd class="mt-1 font-bold">{{ $project->published_at->format('Y') }}</dd></div>@endif @if($project->status)<div><dt class="text-[#8b7e86]">Status</dt><dd class="mt-1 font-bold">{{ $project->status }}</dd></div>@endif</dl></div></header>
@if($project->pdf_path)
<section class="flipbook-section border-y bg-[#1d191b] py-5 text-white sm:py-8"><div class="site-container"><div class="flipbook-shell" data-flipbook data-pdf-url="{{ asset('storage/'.$project->pdf_path) }}">
<div class="flipbook-topbar"><div><strong>Interactive publication</strong><p data-flipbook-status>Opening publication…</p></div><div class="flipbook-topbar-actions">@if($project->is_downloadable)<a href="{{ asset('storage/'.$project->pdf_path) }}" download title="Download PDF">Download</a>@endif<button type="button" data-flip-fullscreen title="Enter fullscreen">Fullscreen</button></div></div>
<div class="flipbook-viewport" data-flipbook-viewport><div data-flipbook-stage class="flipbook-stage"></div><aside class="flipbook-thumbnails" data-flip-thumbnails hidden><div class="flipbook-thumbnails-head"><strong>Pages</strong><button type="button" data-flip-thumbnail-close aria-label="Close page thumbnails">×</button></div><div class="flipbook-thumbnail-grid" data-flip-thumbnail-grid></div></aside></div>
<div class="flipbook-toolbar" role="toolbar" aria-label="Publication controls"><button type="button" data-flip-prev aria-label="Previous page" title="Previous page">‹</button><span data-flip-page class="flipbook-page-count">1 / …</span><button type="button" data-flip-next aria-label="Next page" title="Next page">›</button><i></i><button type="button" data-flip-grid aria-label="Show all pages" title="Show all pages">▦</button><button type="button" data-flip-zoom-out aria-label="Zoom out" title="Zoom out">−</button><button type="button" data-flip-reset data-flip-zoom-value aria-label="Reset zoom" title="Reset zoom">100%</button><button type="button" data-flip-zoom-in aria-label="Zoom in" title="Zoom in">+</button><button type="button" data-flip-fullscreen aria-label="Enter fullscreen" title="Fullscreen">⛶</button></div>
</div></div></section>
@elseif($project->image_path)<section class="site-container pb-12"><img src="{{ asset('storage/'.$project->image_path) }}" alt="{{ $project->title }}" class="mx-auto max-h-[80vh] rounded-[2rem] object-contain shadow-2xl"></section>@endif
<section class="site-container py-20"><div class="grid gap-12 lg:grid-cols-2">@if($project->challenge)<div><p class="eyebrow">The brief</p><p class="mt-4 whitespace-pre-line text-lg leading-8 text-[#6d6269] dark:text-[#cfc4ca]">{{ $project->challenge }}</p></div>@endif @if($project->solution)<div><p class="eyebrow">The design</p><p class="mt-4 whitespace-pre-line text-lg leading-8 text-[#6d6269] dark:text-[#cfc4ca]">{{ $project->solution }}</p></div>@endif</div>@if($project->gallery)<div class="mt-16 grid gap-6 sm:grid-cols-2">@foreach($project->gallery as $image)<img src="{{ asset('storage/'.$image) }}" alt="{{ $project->title }} design {{ $loop->iteration }}" class="w-full rounded-[2rem] border object-cover" loading="lazy">@endforeach</div>@endif</section>
<nav class="site-container grid gap-4 pb-24 sm:grid-cols-2">@if($previous)<a class="service-card" href="{{ route('work.show',$previous) }}"><small>Previous project</small><strong class="mt-2 block font-[family-name:var(--font-display)] text-2xl">{{ $previous->title }}</strong></a>@endif @if($next)<a class="service-card text-right sm:col-start-2" href="{{ route('work.show',$next) }}"><small>Next project</small><strong class="mt-2 block font-[family-name:var(--font-display)] text-2xl">{{ $next->title }}</strong></a>@endif</nav></article>
@endsection
