@extends('layouts.site')
@section('title','Services | '.$settings->name)
@section('description','Publication, directory, poster, campaign, and social media design services by Rovinya Wolff.')
@section('content')
<section class="editorial-gradient"><div class="site-container py-20 sm:py-28"><p class="eyebrow">Design services</p><h1 class="display-title mt-5 max-w-4xl">From a blank page to a complete visual story.</h1><p class="section-copy">Whether you have a detailed brief or only the first idea, we can shape the message, structure the content, and create a design that fits.</p></div></section>
<section class="site-container py-20"><div class="grid gap-6 md:grid-cols-2">@foreach($services as $service)<article class="service-card"><div class="flex items-start justify-between"><span class="text-sm font-bold text-[#e67866]">0{{ $loop->iteration }}</span><span class="size-3 rounded-full bg-[#6f3b67]"></span></div><h2 class="mt-12 font-[family-name:var(--font-display)] text-4xl">{{ $service->title }}</h2><p class="mt-4 text-lg leading-8 text-[#6d6269] dark:text-[#cfc4ca]">{{ $service->description }}</p>@if($service->tags)<div class="mt-7 flex flex-wrap gap-2">@foreach($service->tags as $tag)<span class="rounded-full border px-3 py-1 text-xs">{{ $tag }}</span>@endforeach</div>@endif</article>@endforeach</div></section>
<section class="border-y bg-[#241d24] py-20 text-white"><div class="site-container"><p class="eyebrow text-[#f4a696]">How it works</p><div class="mt-10 grid gap-8 md:grid-cols-3"><div><strong class="font-[family-name:var(--font-display)] text-5xl text-[#e67866]">01</strong><h3 class="mt-4 text-xl font-bold">Discover</h3><p class="mt-2 text-[#d5cad0]">We discuss your goal, audience, content, timing, and the feeling the design should create.</p></div><div><strong class="font-[family-name:var(--font-display)] text-5xl text-[#e67866]">02</strong><h3 class="mt-4 text-xl font-bold">Design</h3><p class="mt-2 text-[#d5cad0]">I build a visual direction, refine the layouts, and keep the content clear and consistent.</p></div><div><strong class="font-[family-name:var(--font-display)] text-5xl text-[#e67866]">03</strong><h3 class="mt-4 text-xl font-bold">Deliver</h3><p class="mt-2 text-[#d5cad0]">You receive polished, practical files prepared for print, digital use, or social publishing.</p></div></div></div></section>
<section class="site-container py-24 text-center"><h2 class="section-title">Need a design that does not fit a label?</h2><p class="section-copy mx-auto">Tell me what you are making. We can find the right format together.</p><a class="button-primary mt-8" href="{{ route('contact') }}">Discuss your project</a></section>
@endsection
